version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: HandsUp_DB
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 10

  flyway:
    image: flyway/flyway:11
    container_name: flyway_migration
    restart: on-failure
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./sql:/flyway/sql
    command: -url=jdbc:postgresql://postgres:5432/${DB_NAME} -user=${DB_USER} -password=${DB_PASS} -connectRetries=30 migrate

volumes:
  pgdata: