name: Lint Codebase
on:
  push:
    branches: [main, dev, ui/learning_progress]

  pull_request:
    branches: [main, dev, ui/learning_progress]
    
permissions:
  contents: read

jobs:
  pre-start:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
      - name: Start Linting
        run: |
          echo "Beginning to lint ${{ github.repository }}"

  lint-codebase:
    name: Lint ${{ matrix.folder }}
    runs-on: ubuntu-latest
    needs: pre-start

    strategy:
      matrix:
        folder: [frontend, backend]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 22  

      - name: Install dependencies ${{ matrix.folder }}
        run: npm ci

      - name: Lint ${{ matrix.folder }}
        working-directory: ${{ matrix.folder }}
        run: npx eslint . --ext .js,.jsx,.ts,.tsx --fix

