name: Test Code
on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]
    
permissions:
  contents: read

jobs:
  pre-start:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Starting Job
        run: |
          echo "Beginning to test ${{ github.repository }}"

  test-codebase:
    name: Test ${{ matrix.folder }}
    runs-on: ubuntu-latest
    needs: pre-start

    # strategy:
    #   matrix:
    #     folder: [frontend, backend]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies for tests
        working-directory: ./
        run: npm ci

      - name: Run Tests
        working-directory: ./
        run: npm run test-coverage

      # Will use later for coverage report
          
      # - name: Create coverage folder if none exists
      #   run: mkdir -p ${{ matrix.folder }}/coverage

      # - name: List files in coverage directory
      #   run: ls -R ${{ matrix.folder }}/coverage

      # - name: Jest Code Coverage
      #   id: coverageComment
      #   uses: MishaKav/jest-coverage-comment@main
      #   with:
      #     hide-comment: true
      #     coverage-summary-path: ${{ matrix.folder }}/coverage/coverage-summary.json

      # - name: Check the output coverage
      #   run: |
      #     echo "Coverage Percentage - ${{ steps.coverageComment.outputs.coverage }}"
      #     echo "Coverage Color - ${{ steps.coverageComment.outputs.color }}"
      #     echo "Summary HTML - ${{ steps.coverageComment.outputs.summaryHtml }}"
    