name: Test Code
on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]
    
permissions:
  contents: read

jobs:
  pre-start:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Starting Job
        run: |
          echo "Beginning to test ${{ github.repository }}"

  test-codebase:
    name: Test Codebase
    runs-on: ubuntu-latest
    needs: pre-start

    # strategy:
    #   matrix:
    #     folder: [frontend, backend]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies for test
        working-directory: ./
        run: npm ci

      - name: Install dependencies for backend
        working-directory: backend/api
        run: npm ci

      - name: Install dependencies for frontend
        working-directory: frontend
        run: npm ci

      - name: Run Tests
        working-directory: ./
        run: npm run test-coverage
    